### ISSUE TITLE
[question] account error when calling contract

### ISSUE THREAD

**Issue by snaphuman** [aeternity/aepp-forgae-shape-vue#1]
Hello,

I would like to ask you a question regarding your code. I'm, reproducing the Home component methods onCallDataAndFunctionAsync and callContract to register memes by their urls. The Wallet Object is configured with the default keypairs of the Contracts Aepp, and pointing to the endpoint of the testnet. In my case, I'm using the browser bundle of the javascript sdk.
When I call static functions of the contract the sdk returns the decoded data, however, when calling stateful functions, like registerMemes it returns the following error:

Error: "Account for ak_6A2vcm1Sz6aqJezkLCssUXcyZTX7X8D5UwbuS2fRJr9KkYpRU not available"

Do you have experimented this issue when developing vue shape?

**Comment by VladislavIvanov** [comment]
Hi, @snaphuman! Thanks for the comment. I am investigating the issue and will return an answer soon.

**Comment by snaphuman** [comment]
Hello @VladislavIvanov. Thank you for your reply. 
Let me give you more context about this issue that is related to the contractCall function.

1. The api version of the browser bundle is aepp-sdk@2.3.2 build:dev
2. When calling the contract with abi parameter 'sophia-contract' returns de described error below "Account not available"
3. Calling contract with abi parameter 'sophia' returns Error: "While calling encodeCalldata (body), POST to https://sdk-testnet.aepps.com/v2/debug/contracts/code/encode-calldata failed with 403: Bad request"
4. I'm using the Wallet  recommended sdk usage as defined in https://github.com/aeternity/aepp-sdk-js/blob/2.3.2/docs/usage.md#high-level-sdk-usage-recommended
5. The settings url and internalUrl are both https://sdk-testnet.aepps.com

Running a local node with a new deployed contract the number 3 arises with the argument 'sophia-addres' on the contractCall function. ¿is the contract decoding code from the contract id?

Thank you for your help

Greetings

**Comment by VladislavIvanov** [comment]
What about the networkId property?

**Comment by snaphuman** [comment]
Running the local node, the networkId property is ae_devnet
Using the testnet endpoint, the networkId property is testnet (I'm not sure if this name is fine or which name sould be here)

**Comment by VladislavIvanov** [comment]
Here is the content of an example config file:
```
    localhostParams: {
        url: "http://localhost:3001",
        networkId: 'ae_devnet'
    },
    testnetParams: {
        url: "https://sdk-testnet.aepps.com",
        networkId: 'ae_uat'
    },
    mainnetParams: {
        url: 'https://sdk-mainnet.aepps.com',
        networkId: 'ae_mainnet'
    }
```

**Comment by snaphuman** [comment]
Thank you for the examples. I have tried localHostParams and testnetParams and I get the same issue.
Also I have rechecked the arguments of the stateful function in the contract by testing it in the Contracts Aepp (which works well and registers the meme succesfully), aside with the same arguments from the contractCall on the frontend function. Thats weird.

**Comment by VladislavIvanov** [comment]
Could you share an example repo and I will try to find the problem?

**Comment by snaphuman** [comment]
Yes, of course. This is the repo https://github.com/snaphuman/MemeVote/tree/master/assets/js.  I have updated it according to this conversation.

Thank you

**Comment by VladislavIvanov** [comment]
Hey, @snaphuman! I have opened a PR to your repo - https://github.com/snaphuman/MemeVote/pull/1.
The signer account was set incorrectly for some reason. I have managed to add a few memes(you will see, sorry for that 😄). 
Please, review the PR and test.
In addition, I will update current repo with the latest version of sdk(currently 3.0.0), but I need some time.

**Comment by snaphuman** [comment]
Hey @VladislavIvanov. Thank you very much for your contribution, I have already merged it to the MemeVote repo. You helped me a lot pointing me to the solution meanwhile I learnt about the aepss javascript sdk, how to deploy a local dev environment with forgae, and practice with Vuje.js. I hope to submit this challenge to the AEternity Development 101 course from https://github.com/dacadeorg/ and continue to the next step. Likewise I'll bring this experience to the Free Software Local Comunity in Bogotá on two weeks with another experiment that involves IoT :D

Pd . I liked the AEternity meme :smile: 

Thanks a lot.
