### ISSUE TITLE
Missing dependencies in aepp-components

### ISSUE THREAD

**Issue by databu** [aeternity/aepp-forgae-shape-vue#3]
I followed the steps described in README.md exactly, but `npm run serve` outputs the following:

```
 ERROR  Failed to compile with 4 errors                                                                                         1:20:43 PM

These dependencies were not found:

* @aeternity/aepp-components in ./src/main.js
* @aeternity/aepp-components/dist/aepp.components.css in ./src/main.js
* @aeternity/aepp-components/dist/aepp.fonts.css in ./src/main.js
* @aeternity/aepp-components/dist/aepp.global.css in ./src/main.js

To install them, you can run: npm install --save @aeternity/aepp-components @aeternity/aepp-components/dist/aepp.components.css @aeternity/aepp-components/dist/aepp.fonts.css @aeternity/aepp-components/dist/aepp.global.css
```

**Comment by VladislavIvanov** [comment]
Hi, @baltar! This error may be due to premature interruption of the command - ```forgae shape vue```.  Please, try to execute the command again and wait until you see ```===== Vue project successfully initialized. =====```.

*In addition:
The shape project is updated with the latest js sdk version - 3.1.0. 
We will provide a tutorial, how to use the ```forgae shape``` command, soon.*
